const actionsTypes = {
  FETCH_CARLIST_START: "FETCH_CARLIST_START",
  FETCH_CARLIST_SUCCESS: "FETCH_CARLIST_SUCCESS",
  FETCH_CARLIST_ERROR: "FETCH_CARLIST_ERROR",
  FETCH_CAR_BY_ID_START: "FETCH_CAR_BY_ID_START",
  FETCH_CAR_BY_ID_SUCCESS: "FETCH_CAR_BY_ID_SUCCESS",
  FETCH_CAR_BY_ID_ERROR: "FETCH_CAR_BY_ID_ERROR",
};

export default actionsTypes;
